# Generated by Django 5.2.4 on 2025-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hidden_for_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
