# Generated by Django 5.2.4 on 2025-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reminder_datetime',
            new_name='reminder_at',
        ),
        migrations.AddField(
            model_name='task',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
