# Generated by Django 5.2.4 on 2025-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
