# Generated by Django 5.2.4 on 2025-08-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chatmessage_hidden_for_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hidden_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
