# Generated by Django 5.2.4 on 2025-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_reminder_datetime_task_reminder_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_sent',
        ),
    ]
