# Generated by Django 5.2.4 on 2025-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chatmessage_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
