# Generated by Django 5.2.4 on 2025-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chatmessage_avatar_chatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_base_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
