# Generated by Django 5.2.4 on 2025-08-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_massege_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='massege',
        ),
    ]
