# Generated by Django 5.2.4 on 2025-07-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
