# Generated by Django 5.2.4 on 2025-09-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chatlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='ChatList',
        ),
    ]
