# Generated by Django 5.2.4 on 2025-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_created_at_block_timestamp_delete_chatlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
