# Generated by Django 5.2.4 on 2025-07-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_task_due_date_recurringtask_task_recurring_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
