# Generated by Django 5.2.4 on 2025-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='medium', max_length=10),
        ),
    ]
