# Generated by Django 5.2.4 on 2025-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='2', max_length=1),
        ),
    ]
