# Generated by Django 5.2.4 on 2025-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_to_do',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
