# Generated by Django 5.2.4 on 2025-07-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_task_time_to_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_to_do',
        ),
    ]
