# Generated by Django 5.2.4 on 2025-07-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
