# Generated by Django 5.2.4 on 2025-07-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_task_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
