# Generated by Django 5.2.4 on 2025-07-19 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shar_with',
            field=models.ManyToManyField(blank=True, related_name='shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
