from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import DeleteChatApi

urlpatterns = [
    path('login/', views.LoginPage, name='login'),
    path('logout/', views.LogoutUser, name='logout'),
    path('register/', views.RegisterPage, name='register'),
    path('', views.home, name='home'),
    path('add_task/', views.add_task, name='add_task'),
    path('complete/<int:task_id>/', views.complete_task, name='complete_task'),
    path('delete_task/<int:pk>/', views.delete_task, name='delete_task'),
    path('update_task/<int:pk>/', views.update_task, name='update_task'),
    path('api/', views.api, name='api'),
    path('api/tasks/', views.task_list, name='task-list'),
    path('api/tasks/<int:pk>/', views.task_detail, name='task-detail'),
    path('api/task-create/', views.task_create, name='task-create'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('activate/<uidb64>/<token>/', views.activate_account, name="activate"),
    path('resend-activation/', views.resend_activation_email, name='resend_activation'),
    path('email-verification-sent/', views.email_verification_sent, name='email_verification_sent'),
    path('reset-password/', views.password_reset_request, name='password_reset_request'),
    path('reset-password/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('profile/', views.profile_view, name='profile'),
    path('dashbord/', views.dashbord, name='dashbord'),
    path('recurring/add/', views.cerate_recurring_task, name='create_recurring_task'),
    path('update-recurring-task/<int:pk>/', views.update_recurring_task, name='update_recurring_task'),
    path('delete-recurring-task/<int:pk>/', views.delete_recurring_task, name='delete_recurring_task'),
    path('add-subtask/<int:task_id>/', views.add_subtask, name='add_subtask'),
    path('history/', views.task_history, name='task_history'),
    path('view-task/<int:pk>/', views.view_task, name='view_task'),
    path('calendar/', views.calendar, name='calendar'),
    path('complete-subtask/<int:subtask_id>/', views.complete_subtask, name='complete_subtask'),
    path('search-users/', views.search_users, name='search_users'),
    path('friend-requests/', views.friend_requests, name='friend_requests'),
    path('api/friend-requests/', views.friend_requests_api, name='friend_requests_api'),
    path('friends/request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('friends/accept/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('friends/decline/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('friends/list/', views.friends_list_api, name='friends_list_api'),
    path('unfriend/<int:user_id>/', views.unfriend, name='unfriend'),
    path('user_profile_ajax/<int:user_id>/', views.user_profile_ajax, name='user_profile_ajax'),
    path('api/chat/messages/', views.ChatMessageApi.as_view(), name='chat-messages-api'),
    path('api/chat/messages/<int:pk>/', views.MessageUpdateDeleteView.as_view(), name='chat-message-edit-delete'),
    path('api/user/profile/<int:user_id>/', views.get_user_profile, name='get_user_profile'),
    path('api/block-user/<int:user_id>/', views.block_user, name='block_user'),
    path('api/unblock/<int:user_id>/', views.unblock_user, name='unblock_user'),
    path('api/chats-list/', views.chats_list, name='chats-list'),
    path('api/check-block-status/<int:user_id>/', views.check_block_status, name='check-block-status'),
    path('api/chat/message/unread_count/',  views.unread_message_count, name='unread-message-count'),
    path('api/chat/messages/mark_read/', views.mark_messages_read, name='mark-messages-read'),
    path('api/chat/message/unread_count/each/', views.unread_message_count_each, name='unread_count_each'),
    path(
        'send-message/<int:receiver_id>/',
        views.send_message,
        name='send_message'
    ),
    path('api/delete-chat/<int:user_id>/', DeleteChatApi.as_view(), name='delete-chat'),
    path("api/friends/requests/count/", views.friend_requests_count, name="friend_requests_count"),
]
